package org.sih.itantra.core.speech.pipeline

import org.sih.itantra.core.common.IndicLanguage

/**
 * Partial hypothesis generated by Pass 1 (low-latency streaming/incremental worker).
 *
 * @property chunkIndex Index of the chunk that produced or triggered this hypothesis.
 * @property partialText Cumulative or incremental recognition text up to this chunk.
 * @property confidence Confidence score in [0.0, 1.0].
 * @property isFinalChunk True if this hypothesis corresponds to the last chunk of the utterance.
 * @property latencyNanos Monotonic processing time taken by Pass 1 for this chunk.
 */
data class Pass1Hypothesis(
    val chunkIndex: Int,
    val partialText: String,
    val confidence: Float = 0.85f,
    val isFinalChunk: Boolean = false,
    val latencyNanos: Long = 0L
)

/**
 * Contextually refined and stabilized hypothesis generated by Pass 2.
 * Pass 2 executes opportunistically during natural silence windows or concurrently on history.
 *
 * @property chunkIndex Index of the latest chunk incorporated into this refinement.
 * @property refinedText Post-processed, context-corrected, or punctuated text.
 * @property isStable True if the text prefix is considered immutable/stable.
 * @property semanticTag Detected semantic category/badge (e.g. "MEDICAL", "EVAC") if recognized.
 * @property latencyNanos Monotonic processing time taken by Pass 2 for this refinement.
 */
data class Pass2Refinement(
    val chunkIndex: Int,
    val refinedText: String,
    val isStable: Boolean = true,
    val semanticTag: String? = null,
    val latencyNanos: Long = 0L
)

/**
 * Comprehensive monotonic stage benchmarks for the speech pipeline (Stages A through H).
 * All timestamps are recorded using monotonic clocks (BenchmarkClock.nowNanos()).
 */
data class PipelinedSpeechMetrics(
    // Stage A: Audio capture start
    val tCaptureStartNanos: Long = 0L,
    // Stage B: First speech detection (VAD trigger)
    val tFirstSpeechNanos: Long = 0L,
    // Stage C: First partial/usable recognition result
    val tFirstPartialNanos: Long = 0L,
    // Stage D: Final speech detection / endpoint (PTT up or final VAD silence)
    val tEndpointNanos: Long = 0L,
    // Stage E: STT completion (Pass 1 and Pass 2 finalization)
    val tSttEndNanos: Long = 0L,
    // Stage F: Semantic processing completion
    val tSemanticEndNanos: Long = 0L,
    // Stage G: Packet-ready time (fragmented/signed/ready for QoS queue)
    val tPacketReadyNanos: Long = 0L,

    // High-level benchmark aggregates
    val totalAudioDurationMs: Long = 0L,
    val pass1ComputeDurationMs: Double = 0.0,
    val pass2ComputeDurationMs: Double = 0.0,
    val overlapDurationMs: Double = 0.0,
    val silenceComputeDurationMs: Double = 0.0,
    val maxQueueDepth: Int = 0,
    val droppedChunksCount: Int = 0,
    val chunksProcessedCount: Int = 0,
    val language: IndicLanguage = IndicLanguage.HINDI
) {
    /**
     * Stage H: Total end-of-speech → packet-ready latency.
     * This is the critical real-time metric: how long the operator waits after finishing speaking.
     */
    val endOfSpeechToPacketReadyMs: Double
        get() = if (tEndpointNanos > 0L && tPacketReadyNanos >= tEndpointNanos) {
            (tPacketReadyNanos - tEndpointNanos) / 1_000_000.0
        } else 0.0

    /**
     * Latency from audio capture start to first partial transcription result.
     */
    val firstPartialLatencyMs: Double
        get() = if (tCaptureStartNanos > 0L && tFirstPartialNanos >= tCaptureStartNanos) {
            (tFirstPartialNanos - tCaptureStartNanos) / 1_000_000.0
        } else 0.0

    /**
     * Total end-to-end elapsed time from capture start to packet ready.
     */
    val totalEndToEndMs: Double
        get() = if (tCaptureStartNanos > 0L && tPacketReadyNanos >= tCaptureStartNanos) {
            (tPacketReadyNanos - tCaptureStartNanos) / 1_000_000.0
        } else 0.0

    /**
     * Real-time Factor (RTF) of the pipeline: Total compute time divided by audio duration.
     * RTF < 1.0 means the pipeline executes faster than real-time audio.
     */
    val realTimeFactor: Double
        get() = if (totalAudioDurationMs > 0L) {
            (pass1ComputeDurationMs + pass2ComputeDurationMs) / totalAudioDurationMs.toDouble()
        } else 0.0
}
