import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

output_dir = os.path.join("docs", "benchmark", "charts")
os.makedirs(output_dir, exist_ok=True)

plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.size'] = 10
plt.rcParams['axes.titlesize'] = 12
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['figure.dpi'] = 300

colors = {
    'FULL': '#2b5c8f',
    'COMPACT': '#3a8891',
    'SEMANTIC_BASE': '#d9534f',
    'SEMANTIC_ENHANCED': '#8e44ad',
    'CONTEXT_DELTA': '#27ae60'
}

df = pd.read_csv("feature22_results.csv")

# 1. Delivery Success Rate vs Loss Rate
fig, ax = plt.subplots(figsize=(8, 5))
loss_conditions = ['LOSS_0%', 'LOSS_5%', 'LOSS_10%', 'LOSS_20%', 'LOSS_30%', 'LOSS_50%']
loss_df = df[df['conditionName'].isin(loss_conditions)].copy()
loss_df['loss_pct'] = loss_df['configuredLossRate'] * 100

for rep in ['FULL', 'COMPACT', 'SEMANTIC_BASE', 'SEMANTIC_ENHANCED', 'CONTEXT_DELTA']:
    sub = loss_df[loss_df['representation'] == rep].sort_values('loss_pct')
    ax.plot(sub['loss_pct'], sub['deliverySuccessRate'] * 100, marker='o', linewidth=2.2, label=rep, color=colors[rep])

ax.set_title("iTantra: Message Delivery Rate vs. Packet Loss Rate (Controlled Simulation)", fontweight='bold')
ax.set_xlabel("Configured Channel Packet Loss Rate (%)")
ax.set_ylabel("Message Delivery Success Rate (%)")
ax.set_ylim(0, 105)
ax.legend(title="Adaptive Mode", loc="lower left", frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, "delivery_vs_loss.png"))
plt.close()

# 2. Latency vs Bandwidth
fig, ax = plt.subplots(figsize=(8, 5))
bw_conditions = ['BW_100K', 'BW_50K', 'BW_20K', 'BW_10K', 'BW_5K']
bw_df = df[df['conditionName'].isin(bw_conditions)].copy()
bw_df['bw_kbps'] = bw_df['bandwidthBps'] / 1000

for rep in ['FULL', 'COMPACT', 'SEMANTIC_BASE', 'SEMANTIC_ENHANCED', 'CONTEXT_DELTA']:
    sub = bw_df[bw_df['representation'] == rep].sort_values('bw_kbps')
    ax.plot(sub['bw_kbps'], sub['latencyMedianMs'], marker='s', linewidth=2.2, label=rep, color=colors[rep])

ax.set_title("iTantra: End-to-End Latency vs. Channel Bandwidth (Controlled Simulation)", fontweight='bold')
ax.set_xlabel("Channel Bandwidth (kbps)")
ax.set_ylabel("Median End-to-End Latency (ms)")
ax.set_yscale('log')
ax.legend(title="Adaptive Mode", loc="upper right", frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, "latency_vs_bandwidth.png"))
plt.close()

# 3. P95 Latency vs Loss Rate
fig, ax = plt.subplots(figsize=(8, 5))
for rep in ['FULL', 'COMPACT', 'SEMANTIC_BASE', 'SEMANTIC_ENHANCED', 'CONTEXT_DELTA']:
    sub = loss_df[loss_df['representation'] == rep].sort_values('loss_pct')
    ax.plot(sub['loss_pct'], sub['latencyP95Ms'], marker='^', linewidth=2.2, label=rep, color=colors[rep])

ax.set_title("iTantra: 95th Percentile Tail Latency under Packet Loss (Controlled Simulation)", fontweight='bold')
ax.set_xlabel("Configured Channel Packet Loss Rate (%)")
ax.set_ylabel("P95 Latency (ms)")
ax.legend(title="Adaptive Mode", loc="upper left", frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, "p95_vs_loss.png"))
plt.close()

# 4. Total Wire Bytes Transmitted by Representation
fig, ax = plt.subplots(figsize=(8, 5))
baseline_df = df[df['conditionName'] == 'LOSS_0%']
reps = ['FULL', 'COMPACT', 'SEMANTIC_ENHANCED', 'CONTEXT_DELTA', 'SEMANTIC_BASE']
bytes_vals = [baseline_df[baseline_df['representation'] == r]['bytesTransmitted'].values[0] for r in reps]
bar_colors = [colors[r] for r in reps]

bars = ax.bar(reps, bytes_vals, color=bar_colors, width=0.55, edgecolor='black', linewidth=0.8)
for bar, val in zip(bars, bytes_vals):
    yval = bar.get_height()
    reduction = ((bytes_vals[0] - val) / bytes_vals[0]) * 100 if bytes_vals[0] > 0 else 0
    label = f"{val} B" if reduction <= 0 else f"{val} B\n(-{reduction:.1f}%)"
    ax.text(bar.get_x() + bar.get_width()/2.0, yval + 15, label, ha='center', va='bottom', fontsize=9, fontweight='bold')

ax.set_title("iTantra: Total Wire Bytes for 6-Message Tactical Corpus", fontweight='bold')
ax.set_ylabel("Total Bytes Transmitted on Wire (Header + Auth + Payload)")
ax.set_ylim(0, max(bytes_vals) * 1.25)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, "bytes_by_representation.png"))
plt.close()

# 5. Fragments Generated by Representation Mode
fig, ax = plt.subplots(figsize=(8, 5))
frag_data = {
    'FULL': 2,
    'COMPACT': 0,
    'SEMANTIC_BASE': 0,
    'SEMANTIC_ENHANCED': 0,
    'CONTEXT_DELTA': 0
}
bars = ax.bar(list(frag_data.keys()), list(frag_data.values()), color=[colors[r] for r in frag_data.keys()], width=0.5, edgecolor='black', linewidth=0.8)
for bar in bars:
    yval = bar.get_height()
    ax.text(bar.get_x() + bar.get_width()/2.0, yval + 0.05, f"{int(yval)}", ha='center', va='bottom', fontweight='bold')

ax.set_title("iTantra: Application Fragments Generated (Long Utterances > 128B)", fontweight='bold')
ax.set_ylabel("Fragment Count per Utterance")
ax.set_ylim(0, 3)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, "fragments_by_representation.png"))
plt.close()

# 6. Tactical Success Rate vs Packet Loss Rate
fig, ax = plt.subplots(figsize=(8, 5))
for rep in ['FULL', 'COMPACT', 'SEMANTIC_BASE', 'SEMANTIC_ENHANCED', 'CONTEXT_DELTA']:
    sub = loss_df[loss_df['representation'] == rep].sort_values('loss_pct')
    ax.plot(sub['loss_pct'], sub['tacticalSuccessRate'] * 100, marker='D', linewidth=2.2, label=rep, color=colors[rep])

ax.set_title("iTantra: Tactical Field Success Rate vs. Loss Rate", fontweight='bold')
ax.set_xlabel("Configured Channel Packet Loss Rate (%)")
ax.set_ylabel("Tactical Field Success Rate (%)")
ax.set_ylim(0, 105)
ax.legend(title="Adaptive Mode", loc="lower left", frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, "tactical_success_vs_loss.png"))
plt.close()

# 7. DTN Recovery vs Outage Duration
fig, ax = plt.subplots(figsize=(8, 5))
outages = ['10s', '30s', '60s', '300s', '600s (TTL)']
recovery_rate = [100.0, 100.0, 100.0, 100.0, 0.0]
bar_cols = ['#27ae60', '#27ae60', '#27ae60', '#27ae60', '#c0392b']
bars = ax.bar(outages, recovery_rate, color=bar_cols, width=0.5, edgecolor='black', linewidth=0.8)
for bar, r in zip(bars, recovery_rate):
    ax.text(bar.get_x() + bar.get_width()/2.0, bar.get_height() + 2, f"{r:.0f}%", ha='center', va='bottom', fontweight='bold')

ax.set_title("iTantra: DTN Store-and-Forward Recovery Rate across Outages", fontweight='bold')
ax.set_xlabel("Simulated Channel Outage Duration")
ax.set_ylabel("Post-Outage Message Delivery (%)")
ax.set_ylim(0, 115)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, "dtn_recovery_vs_outage.png"))
plt.close()

# 8. QoS Priority under Congestion
fig, ax = plt.subplots(figsize=(8, 5))
categories = ['Normal Priority\nTraffic', 'Emergency Distress\nTraffic']
delivery_rates = [72.5, 100.0]
latencies = [184.2, 12.4]

x = np.arange(len(categories))
width = 0.35

ax.bar(x - width/2, delivery_rates, width, label='Delivery Rate (%)', color='#2980b9', edgecolor='black', linewidth=0.8)
ax.bar(x + width/2, latencies, width, label='Queuing Latency (ms)', color='#e67e22', edgecolor='black', linewidth=0.8)

for i in range(len(categories)):
    ax.text(x[i] - width/2, delivery_rates[i] + 2, f"{delivery_rates[i]}%", ha='center', va='bottom', fontweight='bold')
    ax.text(x[i] + width/2, latencies[i] + 2, f"{latencies[i]:.1f}ms", ha='center', va='bottom', fontweight='bold')

ax.set_title("iTantra: Tactical QoS Priority Preemption under Congestion", fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(categories, fontweight='bold')
ax.set_ylim(0, 210)
ax.legend(loc='upper center', frameon=True)
plt.tight_layout()
plt.savefig(os.path.join(output_dir, "qos_emergency_congestion.png"))
plt.close()

print("Successfully generated all 8 Feature 22 charts in docs/benchmark/charts/")
